import { getLocale } from '../i18n'

const en = {
  wakeReview: 'Review background dictation',
  wakeRecoveryHint: 'This text is kept privately on this phone until you insert it into the currently selected journal field or discard it. Check the date and field first.',
  wakeInsert: 'Insert into selected field',
  wakeDiscard: 'Discard this dictation',
  wakeExperiment: 'Experimental “Hey, Tweek”',
  wakeConsent: 'The microphone stays on while waiting, for up to 5 minutes, including over other apps. Say “эй, Твик”, pause, then dictate after Recording appears. A second local check may reject fast speech; accuracy is unvalidated. The microphone notification has Stop. Closing this editor cancels; switching apps keeps the service running. Results are private and need review. Force-stop/reboot ends listening; you must enable it again.',
  wakeOptIn: 'Allow experimental phrase detection for this session',
  startWaiting: 'Start waiting for “эй, Твик”',
  wakeWaiting: 'Microphone on · waiting for “эй, Твик”',
  stopWaiting: 'Stop waiting',
  wakeTimeout: 'Waiting timed out after 5 minutes. The microphone is off. You can start again explicitly.',
  wakeNotifications: 'Allow notifications for the visible microphone Stop control, or use ordinary dictation.',
  wakeUnavailable: 'Experimental phrase detection is unavailable in this APK.',
  cancellingDownload: 'Cancelling download…',
  closeDialog: 'Close the current editor before opening voice input.',
  journal: 'Feelings journal', newEntry: 'New entry', empty: 'A little space for how you feel. Start with a few words.',
  date: 'Date', text: 'What is on your mind?', placeholder: 'What happened? How do you feel? What do you need right now?',
  mood: 'How do you feel? (optional)', noMood: 'Not selected', mood1: 'Very low', mood2: 'Low', mood3: 'Neutral', mood4: 'Good', mood5: 'Very good',
  save: 'Save entry', saved: 'Entry saved', saving: 'Saving…', cancel: 'Cancel', delete: 'Delete entry', deleteConfirm: 'Delete this journal entry?',
  discard: 'Discard this unsaved draft?', saveFailed: 'Could not save. Your draft is still here.', deleteFailed: 'Could not delete the entry. Please try again.',
  privacy: 'Entries stay in this app’s local storage. They are not additionally encrypted. JSON backups contain the journal as readable text; System backups may also contain it; Android Preview disables system backup. Protect exported files.',
  draft: 'Drafts are saved locally. Choose Save entry to finish.',
  voiceDetails: 'Recording limits and voice activation',
  voice: 'Russian dictation on this phone', voicePrivacy: 'Audio is processed on this phone and is not saved or sent to a speech service. Check the transcript before saving.',
  model: 'Russian language model: Vosk small-ru-0.22 · Apache 2.0 · 46.2 MB download, 91.3 MB unpacked. One download from alphacephei.com; allow extra space during installation.',
  download: 'Download Russian model', downloading: 'Downloading and checking model…', cancelDownload: 'Cancel download',
  record: 'Dictate in Russian', recording: 'Recording', loading: 'Preparing microphone…', processing: 'Finishing recognition…', stop: 'Stop and use text', cancelRecording: 'Cancel dictation',
  ready: 'Ready · microphone off', permission: 'Microphone permission was not granted. You can type or allow it in Android app settings.',
  unsupported: 'Local dictation is available in the updated Android APK. You can type here; no cloud recognition is used.',
  failed: 'Dictation could not finish. Your typed draft is unchanged. Try again.', noSpeech: 'No speech recognized. Try again or type your entry.',
  downloadFailed: 'Model download failed. Check your connection and free space, then retry.', modelMissing: 'Download the Russian model first.',
  foreground: 'Keep the app open while dictating. Leaving it cancels capture. Maximum 2 minutes per recording; you can dictate again to append.',
  wake: 'Preview offers optional experimental “эй, Твик” detection via a microphone service. Screen lock and actual Android lifecycle behavior need device testing; ordinary dictation remains available.',
  taskVoice: 'Local voice task', taskText: 'Review your task', addTask: 'Add task', noTask: 'Say or type a task first.',
  pause: 'Pause: stop dictation, then dictate again to continue.', cancelled: 'Dictation cancelled. The existing draft is unchanged.',
}
const ru: Record<keyof typeof en, string> = {
  wakeReview: 'Проверьте фоновую диктовку',
  wakeRecoveryHint: 'Этот текст хранится приватно на телефоне, пока вы не вставите его в выбранный раздел дневника или не удалите. Сначала проверьте дату и раздел.',
  wakeInsert: 'Вставить в выбранный раздел',
  wakeDiscard: 'Удалить эту диктовку',
  wakeExperiment: 'Эксперимент: «эй, Твик»',
  wakeConsent: 'Во время ожидания микрофон включён, максимум 5 минут, в том числе поверх других приложений. Скажите «эй, Твик», сделайте паузу и диктуйте после индикатора записи. Повторная локальная проверка может пропускать быструю речь; качество не проверено. В уведомлении есть «Остановить». Закрытие редактора отменяет сеанс, переключение приложений сохраняет службу. Результат приватный и требует проверки. После принудительной остановки или перезагрузки нужно включить режим снова.',
  wakeOptIn: 'Разрешить экспериментальное распознавание фразы в этом сеансе',
  startWaiting: 'Ждать фразу «эй, Твик»',
  wakeWaiting: 'Микрофон включён · ждём «эй, Твик»',
  stopWaiting: 'Прекратить ожидание',
  wakeTimeout: 'Ожидание завершено через 5 минут. Микрофон выключен. Можно запустить снова вручную.',
  wakeNotifications: 'Разрешите уведомления для видимой кнопки остановки микрофона или используйте обычную диктовку.',
  wakeUnavailable: 'В этой APK экспериментальное распознавание фразы недоступно.',
  cancellingDownload: 'Отменяем загрузку…',
  closeDialog: 'Сначала закройте текущий редактор, чтобы открыть голосовой ввод.',
  journal: 'Дневник чувств', newEntry: 'Новая запись', empty: 'Немного места для ваших чувств. Начните с нескольких слов.',
  date: 'Дата', text: 'Что у вас на душе?', placeholder: 'Что произошло? Что вы чувствуете? Чего сейчас не хватает?',
  mood: 'Как вы себя чувствуете? (необязательно)', noMood: 'Не выбрано', mood1: 'Очень тяжело', mood2: 'Тяжело', mood3: 'Нейтрально', mood4: 'Хорошо', mood5: 'Очень хорошо',
  save: 'Сохранить запись', saved: 'Запись сохранена', saving: 'Сохранение…', cancel: 'Отмена', delete: 'Удалить запись', deleteConfirm: 'Удалить эту запись дневника?',
  discard: 'Отменить изменения в несохранённом черновике?', saveFailed: 'Не удалось сохранить. Черновик остался здесь.', deleteFailed: 'Не удалось удалить запись. Попробуйте ещё раз.',
  privacy: 'Записи хранятся локально в приложении без дополнительного шифрования. В JSON-копиях дневник записан открытым текстом; в других сборках он также может попасть в системную копию устройства. В Android Preview системное резервное копирование отключено. Берегите экспортированные файлы.',
  draft: 'Черновик сохраняется локально. Нажмите «Сохранить запись», чтобы завершить.',
  voiceDetails: 'Ограничения записи и голосовая активация',
  voice: 'Русская диктовка на этом телефоне', voicePrivacy: 'Звук обрабатывается на телефоне, не сохраняется и не отправляется в сервис распознавания. Проверьте текст перед сохранением.',
  model: 'Русская модель: Vosk small-ru-0.22 · Apache 2.0 · загрузка 46,2 МБ, после распаковки 91,3 МБ. Однократная загрузка с alphacephei.com; при установке нужно дополнительное свободное место.',
  download: 'Скачать русскую модель', downloading: 'Загрузка и проверка модели…', cancelDownload: 'Отменить загрузку',
  record: 'Диктовать по-русски', recording: 'Идёт запись', loading: 'Подготовка микрофона…', processing: 'Завершаем распознавание…', stop: 'Остановить и вставить текст', cancelRecording: 'Отменить диктовку',
  ready: 'Готово · микрофон выключен', permission: 'Доступ к микрофону не разрешён. Можно напечатать текст или разрешить доступ в настройках Android.',
  unsupported: 'Локальная диктовка доступна в обновлённом Android APK. Здесь можно печатать; облачное распознавание не используется.',
  failed: 'Не удалось завершить диктовку. Напечатанный черновик не изменился. Попробуйте снова.', noSpeech: 'Речь не распознана. Попробуйте ещё раз или напечатайте текст.',
  downloadFailed: 'Модель не загрузилась. Проверьте интернет и свободное место, затем повторите.', modelMissing: 'Сначала скачайте русскую модель.',
  foreground: 'Во время диктовки держите приложение открытым. При уходе запись отменяется. Одна запись — до 2 минут; можно диктовать снова, дополняя текст.',
  wake: 'В Preview доступно добровольное экспериментальное ожидание «эй, Твик» через службу микрофона. Блокировка экрана и фактическая работа Android требуют проверки на телефоне; обычная диктовка остаётся доступной.',
  taskVoice: 'Локальная голосовая задача', taskText: 'Проверьте задачу', addTask: 'Добавить задачу', noTask: 'Сначала произнесите или напечатайте задачу.',
  pause: 'Для паузы остановите диктовку, затем запустите её снова, чтобы продолжить.', cancelled: 'Диктовка отменена. Предыдущий черновик не изменился.',
}
export const j = (key: keyof typeof en) => (getLocale() === 'ru' ? ru : en)[key]
