import { getLocale } from '../i18n'

const en = {
  cancellingDownload: 'Cancelling download…',
  closeDialog: 'Close the current editor before opening voice input.',
  journal: 'Feelings journal', newEntry: 'New entry', empty: 'A little space for how you feel. Start with a few words.',
  date: 'Date', text: 'What is on your mind?', placeholder: 'What happened? How do you feel? What do you need right now?',
  mood: 'How do you feel? (optional)', noMood: 'Not selected', mood1: 'Very low', mood2: 'Low', mood3: 'Neutral', mood4: 'Good', mood5: 'Very good',
  save: 'Save entry', saved: 'Entry saved', saving: 'Saving…', cancel: 'Cancel', delete: 'Delete entry', deleteConfirm: 'Delete this journal entry?',
  discard: 'Discard this unsaved draft?', saveFailed: 'Could not save. Your draft is still here.', deleteFailed: 'Could not delete the entry. Please try again.',
  privacy: 'Entries stay in this app’s local storage. They are not additionally encrypted. JSON backups contain the journal as readable text; Android system backups may also contain it. Protect exported files.',
  draft: 'Draft — saved only when you choose Save. Closing the app can lose an unsaved draft.',
  voiceDetails: 'Recording limits and voice activation',
  voice: 'Russian dictation on this phone', voicePrivacy: 'Audio is processed on this phone and is not saved or sent to a speech service. Check the transcript before saving.',
  model: 'Russian language model: Vosk small-ru-0.22 · Apache 2.0 · 46.2 MB download, 91.3 MB unpacked. One download from alphacephei.com; allow extra space during installation.',
  download: 'Download Russian model', downloading: 'Downloading and checking model…', cancelDownload: 'Cancel download',
  record: 'Dictate in Russian', recording: 'Recording', loading: 'Preparing microphone…', processing: 'Finishing recognition…', stop: 'Stop and use text', cancelRecording: 'Cancel dictation',
  ready: 'Ready · microphone off', permission: 'Microphone permission was not granted. You can type or allow it in Android app settings.',
  unsupported: 'Local dictation is available in the updated Android APK. You can type here; no cloud recognition is used.',
  failed: 'Dictation could not finish. Your typed draft is unchanged. Try again.', noSpeech: 'No speech recognized. Try again or type your entry.',
  downloadFailed: 'Model download failed. Check your connection and free space, then retry.', modelMissing: 'Download the Russian model first.',
  foreground: 'Keep the app open while dictating. Leaving it cancels capture. Maximum 2 minutes per recording; you can dictate again to append.',
  wake: '“Hey, Tweek” activation is not available in this version: the Russian wake phrase has not been validated. Use the microphone button.',
  taskVoice: 'Local voice task', taskText: 'Review your task', addTask: 'Add task', noTask: 'Say or type a task first.',
  pause: 'Pause: stop dictation, then dictate again to continue.', cancelled: 'Dictation cancelled. The existing draft is unchanged.',
}
const ru: Record<keyof typeof en, string> = {
  cancellingDownload: 'Отменяем загрузку…',
  closeDialog: 'Сначала закройте текущий редактор, чтобы открыть голосовой ввод.',
  journal: 'Дневник чувств', newEntry: 'Новая запись', empty: 'Немного места для ваших чувств. Начните с нескольких слов.',
  date: 'Дата', text: 'Что у вас на душе?', placeholder: 'Что произошло? Что вы чувствуете? Чего сейчас не хватает?',
  mood: 'Как вы себя чувствуете? (необязательно)', noMood: 'Не выбрано', mood1: 'Очень тяжело', mood2: 'Тяжело', mood3: 'Нейтрально', mood4: 'Хорошо', mood5: 'Очень хорошо',
  save: 'Сохранить запись', saved: 'Запись сохранена', saving: 'Сохранение…', cancel: 'Отмена', delete: 'Удалить запись', deleteConfirm: 'Удалить эту запись дневника?',
  discard: 'Отменить изменения в несохранённом черновике?', saveFailed: 'Не удалось сохранить. Черновик остался здесь.', deleteFailed: 'Не удалось удалить запись. Попробуйте ещё раз.',
  privacy: 'Записи хранятся локально в приложении без дополнительного шифрования. В JSON-копиях дневник записан открытым текстом; он также может попасть в системную копию Android. Берегите экспортированные файлы.',
  draft: 'Черновик — запись появится в дневнике только после сохранения. Закрытие приложения может привести к потере черновика.',
  voiceDetails: 'Ограничения записи и голосовая активация',
  voice: 'Русская диктовка на этом телефоне', voicePrivacy: 'Звук обрабатывается на телефоне, не сохраняется и не отправляется в сервис распознавания. Проверьте текст перед сохранением.',
  model: 'Русская модель: Vosk small-ru-0.22 · Apache 2.0 · загрузка 46,2 МБ, после распаковки 91,3 МБ. Однократная загрузка с alphacephei.com; при установке нужно дополнительное свободное место.',
  download: 'Скачать русскую модель', downloading: 'Загрузка и проверка модели…', cancelDownload: 'Отменить загрузку',
  record: 'Диктовать по-русски', recording: 'Идёт запись', loading: 'Подготовка микрофона…', processing: 'Завершаем распознавание…', stop: 'Остановить и вставить текст', cancelRecording: 'Отменить диктовку',
  ready: 'Готово · микрофон выключен', permission: 'Доступ к микрофону не разрешён. Можно напечатать текст или разрешить доступ в настройках Android.',
  unsupported: 'Локальная диктовка доступна в обновлённом Android APK. Здесь можно печатать; облачное распознавание не используется.',
  failed: 'Не удалось завершить диктовку. Напечатанный черновик не изменился. Попробуйте снова.', noSpeech: 'Речь не распознана. Попробуйте ещё раз или напечатайте текст.',
  downloadFailed: 'Модель не загрузилась. Проверьте интернет и свободное место, затем повторите.', modelMissing: 'Сначала скачайте русскую модель.',
  foreground: 'Во время диктовки держите приложение открытым. При уходе запись отменяется. Одна запись — до 2 минут; можно диктовать снова, дополняя текст.',
  wake: 'Активация «эй, Твик» пока недоступна: русская фраза ещё не проверена. Используйте кнопку микрофона.',
  taskVoice: 'Локальная голосовая задача', taskText: 'Проверьте задачу', addTask: 'Добавить задачу', noTask: 'Сначала произнесите или напечатайте задачу.',
  pause: 'Для паузы остановите диктовку, затем запустите её снова, чтобы продолжить.', cancelled: 'Диктовка отменена. Предыдущий черновик не изменился.',
}
export const j = (key: keyof typeof en) => (getLocale() === 'ru' ? ru : en)[key]
